### ISSUE TITLE
Can't use wallet on Ubuntu 18.04

### ISSUE THREAD

**Issue by kaN5300** [altbet/abet#11]
Hello. There is no binary version of QT wallet for the latest LTS of Ubuntu (18.04) i am using. Compiling from source also failing at autogen stage with:

./autogen.sh 
configure.ac:28: installing 'build-aux/install-sh'
configure.ac:28: installing 'build-aux/missing'
Makefile.am:8: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:8:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:8:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:8:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:8:   its definition is in aclocal's search path.
Makefile.am: installing 'build-aux/depcomp'
/usr/share/automake-1.15/am/depend2.am: error: am__fastdepCXX does not appear in AM_CONDITIONAL
/usr/share/automake-1.15/am/depend2.am:   The usual way to define 'am__fastdepCXX' is to add 'AC_PROG_CXX'
/usr/share/automake-1.15/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
/usr/share/automake-1.15/am/depend2.am: error: AMDEP does not appear in AM_CONDITIONAL
/usr/share/automake-1.15/am/depend2.am:   The usual way to define 'AMDEP' is to add one of the compiler tests
/usr/share/automake-1.15/am/depend2.am:     AC_PROG_CC, AC_PROG_CXX, AC_PROG_OBJC, AC_PROG_OBJCXX,
/usr/share/automake-1.15/am/depend2.am:     AM_PROG_AS, AM_PROG_GCJ, AM_PROG_UPC
/usr/share/automake-1.15/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
Makefile.am: error: C++ source seen but 'CXX' is undefined
Makefile.am:   The usual way to define 'CXX' is to add 'AC_PROG_CXX'
Makefile.am:   to 'configure.ac' and run 'autoconf' again.
parallel-tests: installing 'build-aux/test-driver'
autoreconf: automake failed with exit status: 1

**Comment by kaN5300** [comment]
Using binary from 16.04 on 18.04 cousing this:

./altbet-v2.0.0.1-ubu1604-qt 
./altbet-v2.0.0.1-ubu1604-qt: error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file: No such file or directory

So, no libboost 1.58 found in 18.04 reps...

https://packages.ubuntu.com/search?suite=cosmic&section=all&arch=any&keywords=libboost_system.so.1.58.0&searchon=contents

**Comment by kaN5300** [comment]
Hello.
Still waiting for building instructions and/or 18.04 binaries.

**Comment by B0guS** [comment]
because you have to install boost 1.58, on ubuntu 18.04 it gets 1.64 if i remember.
try this : https://www.boost.org/doc/libs/1_58_0/more/getting_started/unix-variants.html
