### ISSUE TITLE
altbet-qt not running properly

### ISSUE THREAD

**Issue by gl00m** [altbet/abet#4]
When I run it on Ubuntu 16.04 it shows only splash window and alert window: 

> A fatal error occurred. Altbet can no longer continue safely and will quit.
> 
> EXCEPTION: N5boost10filesystem16filesystem_errorE       
> filesystem::recursive_directory_iterator directory error: Access denied    
> altbet in Runaway exception

in debug.log:

> GUI: Qt has caught an exception thrown from an event handler. Throwing 
> exceptions from an event handler is not supported in Qt. You must 
> reimplement QApplication::notify() and catch all exceptions there.

Looks like it's working, but main window not appears and when I click "OK" It just closed
I tried this also on fresh install (without config, downloaded blocks or db) - same result
ps strange, but when I run app (v2) first time it worked without problems

**Comment by MotoAcidic** [comment]
Have you tried to compile your own QT from the provided scripts in the scripts folder on the root of the source?

**Comment by gl00m** [comment]
Yes! It helps...

**Comment by MotoAcidic** [comment]
Let me know if you where able to compile a good version so we can close this.

**Comment by MotoAcidic** [comment]
@altbet  go ahead and close this issue please
